"""Export complete saved results to SI S7--S13, with row-level value provenance.

Formatting only. No estimates, intervals, tests, or resampling are computed.
"""
import re
import csv
import hashlib
import json
from pathlib import Path

PROTOCOLS = [('participant_5fold', 'New participants'),
             ('leave_country_out', 'Held-out country'),
             ('event_group_5fold', 'New events'),
             ('crossed_participant_event_5x5', 'New participants + events')]
FEATURE_LABELS = {
    'event_key': 'Event identity', 'scenario': 'Block identity', 'country': 'Reported country',
    'age': 'Age', 'driving_exp_years': 'Years since licence acquisition',
    'gender': 'Gender', 'education': 'Education', 'own_car': 'Car ownership',
    'drive_freq_12m': 'Driving frequency', 'km_12m': 'Past-year driving distance',
    'km_life': 'Lifetime driving distance', 'drive_style': 'Self-reported driving style',
    'drive_type': 'Typical round-trip distance', 'know_ad': 'Automation knowledge',
    'acc_years': 'ACC experience (years)', 'acc_dist': 'ACC experience (distance)',
    'lks_years': 'LKS experience (years)', 'lks_dist': 'LKS experience (distance)',
    'acclks_years': 'ACC + LKS experience (years)', 'acclks_dist': 'ACC + LKS experience (distance)',
    'trust_pre_overall': 'Initial overall trust', 'trust_pre_acc': 'Initial ACC trust',
    'trust_pre_lks': 'Initial LKS trust', 'accept_pre_delegate': 'Initial delegation acceptance',
    'accept_pre_monitor_raw': 'Initial supervision need',
    'accept_pre_distract': 'Initial non-driving acceptance',
    'risk_person_block_balanced_mean': 'Participant mean risk',
    'mean_risk': 'Mean risk', 'excursion': 'Excursion', 'late_change': 'Late change'}
ITEMS = [('overall', 'Overall trust'), ('acc', 'ACC trust'), ('lks', 'LKS trust')]
SETS = [('pre_task', 'Pre-task attributes'),
        ('pre_task_plus_response', 'Pre-task + response fraction'),
        ('pre_task_plus_mean_risk_response', 'Pre-task + response + mean risk'),
        ('pre_task_plus_dynamics', 'Pre-task + three risk summaries'),
        ('pre_task_plus_both', 'Pre-task + response + three risk summaries')]
COUNTRIES = {'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
             'United States of America': 'United States'}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def longtable(label, caption, spec, headers, body, footnote):
    n = len(headers)
    header = ' & '.join(headers) + r' \\'
    return '\n'.join([
        '% Generated by presentation/full_tables.py.',
        '% Saved-result formatting only. Requires longtable and booktabs.',
        r'\begingroup', r'\small', r'\setlength{\tabcolsep}{3pt}',
        r'\renewcommand{\arraystretch}{1.06}',
        rf'\begin{{longtable}}{{{spec}}}', rf'\caption{{{caption}}}\label{{tab:{label}}}\\',
        r'\toprule', header, r'\midrule', r'\endfirsthead',
        rf'\multicolumn{{{n}}}{{l}}{{\tablename\ \thetable\ (continued)}}\\',
        r'\toprule', header, r'\midrule', r'\endhead',
        r'\midrule', rf'\multicolumn{{{n}}}{{r}}{{Continued on next page}}\\', r'\endfoot',
        r'\bottomrule', r'\endlastfoot', *body, r'\end{longtable}',
        r'\noindent\parbox{\linewidth}{\small\raggedright ' + footnote + '}',
        r'\endgroup', '\n'])


def append_full_saved_tables(root, read, write, table, row, num, ci, qvalue, tex,
                            metadata, inherited_before):
    source = root / 'outputs/core/tables'
    out = root / 'outputs/presentation/tables'
    reportdir = root / 'outputs/presentation/reports'
    audit_rows = []
    produced = {}

    def keep(table_id, source_name, source_row, selector, fields, rendered):
        audit_rows.append(dict(table=table_id, source_file=str((source/source_name).relative_to(root)),
            source_sha256=sha(source/source_name), selector=json.dumps(selector,ensure_ascii=False),
            source_fields=json.dumps(fields),
            exact_source_values=json.dumps([source_row[f] for f in fields],ensure_ascii=False),
            rendered_row=rendered, status='pending'))

    def emit(number, suffix, caption, spec, headers, body, footnote, files, detail):
        name=f'table_s{number}_{suffix}.tex'
        content=longtable(f's{number}_{suffix}',caption,spec,headers,body,footnote)
        write(name,content,files,{'n_display_rows':detail.pop('n_display_rows'),
             'format':'longtable; repeated headers; page breaks allowed; no scaling',**detail})
        metadata['tables'][-1]['layout']='longtable at natural column widths; no graphic scaling'
        produced[f'S{number}']=name

    # S7: join countries solely by their explicit saved country key.
    shapes=read('a2_country_shape_similarity.csv')
    levels=read('a2_country_stimulus_standardized.csv')
    lm={r['country']:r for r in levels}
    assert len(shapes)==len(lm)==29 and {r['country'] for r in shapes}==set(lm)
    body=[]
    for r in shapes:
        z=lm[r['country']];assert r['n_participants']==z['n_participants']
        def safe_ci(v):
            if not v['ci_low'] or not v['ci_high']:
                assert int(v['n_participants'])==1
                return r'\textemdash'
            return ci(v)
        rendered=row(tex(COUNTRIES.get(r['country'],r['country'])),f"{int(r['n_participants']):,}",
                     num(r['shape_r']),safe_ci(r),num(z['stimulus_adjusted_difference']),safe_ci(z))
        body.append(rendered)
        keep('S7','a2_country_shape_similarity.csv',r,{'country':r['country']},
             ['n_participants','shape_r','ci_low','ci_high'],rendered)
        keep('S7','a2_country_stimulus_standardized.csv',z,{'country':r['country']},
             ['n_participants','stimulus_adjusted_difference','ci_low','ci_high'],rendered)
    emit(7,'country_profiles',
        'Complete country-level shape similarity and stimulus-matched risk differences. '
        r'$r$ is the block-centred profile correlation with other-country responses; '
        r'$\Delta$ is the mean risk difference from other-country responses to the same event and clip. '
        'Both summaries retain all 29 reported countries.',
        r'@{}lrrrrr@{}',['Country','$N$','$r$',r'95\% CI',r'$\Delta$',r'95\% CI'],body,
        r'$N$ counts participants. Shape intervals use 1,000 attempted within-country participant '
        'bootstrap draws, excluding undefined correlations; difference intervals use 2,000 draws. '
        'External reference estimates remain fixed. Intervals are unavailable for the six singleton countries '
        r'(\textemdash). Differences are in risk-rating points. Short country names follow Table S1.',
        ['a2_country_shape_similarity.csv','a2_country_stimulus_standardized.csv'],
        {'n_display_rows':29,'join_key':'country','source_rows':[29,29],
         'missing_intervals':'six singleton countries; retained without invented intervals'})

    # S8: all four protocols and all six models, not just selected curves.
    perf=read('m2_performance.csv');assert len(perf)==24
    models=['Training mean','Training event/block mean','Ridge identity only','LightGBM identity only','Ridge','LightGBM']
    assert set(models)=={r['model'] for r in perf}
    lookup={(r['protocol'],r['model']):r for r in perf};body=[]
    for key,label in PROTOCOLS:
        body.append(r'\multicolumn{4}{@{}l}{\textbf{'+label+r'}} \\')
        for model in models:
            r=lookup[(key,model)]
            assert int(r['n'])==34566 and int(r['n_participants'])==2164
            vals=[num(r[m],4)+' '+ci(r,m+'_ci_low',m+'_ci_high',4) for m in ['r2','rmse','mae']]
            rendered=row(tex(model),*vals);body.append(rendered)
            keep('S8','m2_performance.csv',r,{'protocol':key,'model':model},
                 [f for m in ['r2','rmse','mae'] for f in [m,m+'_ci_low',m+'_ci_high']],rendered)
        body.append(r'\addlinespace[4pt]')
    emit(8,'all_risk_prediction',
        r'Complete held-out event-risk prediction results: all 24 protocol--model combinations. '
        r'Cells show the metric and its pointwise 95\% confidence interval.',
        r'@{}lrrr@{}',['Model',r'$R^2$ [95\% CI]',r'RMSE [95\% CI]',r'MAE [95\% CI]'],body,
        r'Each combination evaluates 34,566 event means from 2,164 people. $R^2$ is unitless; '
        'RMSE and MAE are in risk-rating points. Identity-only models exclude personal attributes; '
        'Ridge and LightGBM without this qualifier include personal attributes. The training event/block '
        'mean falls back to block means for unseen events. Intervals use 1,000 participant-cluster '
        'bootstrap draws of fixed held-out predictions, without model refitting or stimulus resampling. '
        'New-event holdout can reuse people; crossed holdout excludes both participant and event groups.',
        ['m2_performance.csv'],{'n_display_rows':24,'source_rows':24,'protocols':dict(PROTOCOLS),
          'models':models,'metrics':['r2','rmse','mae'],'ci_fields':'saved metric_ci_low/high'})

    # S9: all attributes, including country and both identity attributes.
    importance=read('m2_shap_global_importance.csv');assert len(importance)==26
    body=[]
    for r in importance:
        rendered=row(tex(FEATURE_LABELS[r['feature']]),tex(r['family']),
                     num(r['mean_abs_shap'],4),num(r['fold_mean_abs_sd'],4))
        body.append(rendered)
        keep('S9','m2_shap_global_importance.csv',r,{'feature':r['feature']},
             ['mean_abs_shap','fold_mean_abs_sd'],rendered)
    emit(9,'all_shap_importance',
        'Complete participant-held-out TreeSHAP attribution magnitudes for all 26 input attributes. '
        'Features retain the ordering in the saved results.',
        r'@{}p{.36\linewidth}p{.30\linewidth}rr@{}',
        ['Attribute','Family',r'Mean $|\phi|$','Fold SD'],body,
        'Mean absolute attribution is computed over all 34,566 held-out event rows from 2,164 people. '
        'Categorical dummy contributions are summed to their original attribute before absolute magnitudes '
        'are computed. Fold SD is the sample standard deviation of the five fold-specific mean absolute '
        'attributions; it is not a confidence interval or a measure of intervention effects. '
        'Both numeric columns are in risk-rating points.',
        ['m2_shap_global_importance.csv'],{'n_display_rows':26,'source_rows':26,
         'uncertainty_column':'fold_mean_abs_sd; across five folds; sample SD (ddof=1), not CI',
         'feature_display_mapping':FEATURE_LABELS})

    # S10: three predictors by all three cross-outcome comparisons.
    contrasts=read('a2_trust_between_item_coefficients.csv');assert len(contrasts)==9
    body=[]
    for r in contrasts:
        label={'overall':'Overall','acc':'ACC','lks':'LKS'}
        rendered=row(label[r['first']]+' $-$ '+label[r['second']],
                     FEATURE_LABELS[r['feature']],num(r['estimate']),ci(r),qvalue(r['q']),f"{int(r['n']):,}")
        body.append(rendered)
        keep('S10','a2_trust_between_item_coefficients.csv',r,
             {'first':r['first'],'second':r['second'],'feature':r['feature']},
             ['n','estimate','ci_low','ci_high','q'],rendered)
    emit(10,'all_trust_coefficient_contrasts',
        'Complete cross-outcome contrasts of the adjusted risk--trust coefficients. '
        'The sign is the first named outcome coefficient minus the second.',
        r'@{}llrrrr@{}',['Outcome contrast','Predictor','Estimate',r'95\% CI','$q$','$N$'],body,
        'Estimates are in trust-rating points per SD of the predictor. Joint heteroskedasticity-robust '
        'cross-outcome sandwich covariance preserves dependence between outcomes from the same person. '
        'All models use 2,158 complete participants and adjust for their corresponding initial trust item '
        r'and the covariates listed in Table S6. Intervals are pointwise normal 95\% intervals; '
        '$q$ is the Benjamini--Hochberg adjustment across all nine displayed contrasts.',
        ['a2_trust_between_item_coefficients.csv'],{'n_display_rows':9,'source_rows':9,
        'q_scope':'nine saved cross-outcome contrasts','sign':'first minus second'})

    # S11: all 9 choose 2 correlations, with underflowed p/q displayed as bounds.
    correlations=read('d2_spearman_associations.csv');assert len(correlations)==36
    assert len({frozenset([r['variable_a'],r['variable_b']]) for r in correlations})==36
    body=[]
    for r in correlations:
        rendered=row(tex(FEATURE_LABELS[r['variable_a']]),tex(FEATURE_LABELS[r['variable_b']]),
                     num(r['rho']),qvalue(r['p']),qvalue(r['q_bh']),f"{int(r['n_participants']):,}")
        body.append(rendered)
        keep('S11','d2_spearman_associations.csv',r,
             {'variable_a':r['variable_a'],'variable_b':r['variable_b']},
             ['rho','p','q_bh','n_participants'],rendered)
    emit(11,'all_spearman_pairs',
        'Complete pairwise Spearman correlations among age, licence-based driving experience, '
        'participant mean risk and the six initial attitude items.',
        r'@{}p{.31\linewidth}p{.31\linewidth}rrrr@{}',
        ['Variable 1','Variable 2',r'$\rho$','$p$','$q$','$N$'],body,
        'The table contains all 36 distinct off-diagonal pairs. Participant mean risk gives equal weight '
        'to the four questionnaire blocks. Attitude zeros remain valid and supervision need retains its '
        'original direction. $q$ is the Benjamini--Hochberg adjustment across the 36 saved tests. '
        'Saved values below 0.001, including numerical underflow to zero, are displayed as $<0.001$, '
        'without changing the underlying source values. These are descriptive associations.',
        ['d2_spearman_associations.csv'],{'n_display_rows':36,'source_rows':36,
          'q_scope':'all 36 pairs','small_p_display':'<0.001, including saved floating-point zero'})

    # S12: all five saved feature sets, three outcomes and both protocols.
    trust=read('a2_trust_cv_performance.csv');assert len(trust)==30
    lookup={(r['protocol'],r['item'],r['feature_set']):r for r in trust};body=[]
    for protocol,plabel in PROTOCOLS[:2]:
        for item,ilabel in ITEMS:
            body.append(r'\multicolumn{4}{@{}l}{\textbf{'+plabel+'; '+ilabel+r'}} \\')
            for feature,label in SETS:
                r=lookup[(protocol,item,feature)];assert int(r['n'])==2164
                rendered=row(tex(label),*[num(r[m],4) for m in ['r2','rmse','mae']]);body.append(rendered)
                keep('S12','a2_trust_cv_performance.csv',r,
                     {'protocol':protocol,'item':item,'feature_set':feature},
                     ['n','r2','rmse','mae'],rendered)
            body.append(r'\addlinespace[4pt]')
    emit(12,'all_trust_prediction',
        'Complete post-task trust prediction results for all 30 combinations of five feature sets, '
        'three trust outcomes and two evaluation protocols.',
        r'@{}lrrr@{}',['Feature set',r'$R^2$','RMSE','MAE'],body,
        'Each combination evaluates 2,164 participants. Response fraction is the proportion of assigned '
        'video-risk ratings that were operated. The three risk summaries are mean risk, excursion and '
        'late change; any peak selection for shape summaries uses training data only. RMSE and MAE are '
        'in trust-rating points. This table reports the complete saved metric values; the saved performance '
        'CSV does not contain metric confidence intervals. Paired incremental intervals for selected '
        'comparisons appear in Table S5. No new intervals are calculated here.',
        ['a2_trust_cv_performance.csv'],{'n_display_rows':30,'source_rows':30,
          'ci_status':'not present in saved performance table; not invented',
          'feature_set_labels':dict(SETS),'protocols':dict(PROTOCOLS[:2])})

    # S13: only planned pooled summaries, clearly separating later exploration.
    local=root/'outputs/whatif/tables'
    def local_read(name):
        with (local/name).open(newline='') as f:return list(csv.DictReader(f))
    def keep_local(name,r,selector,fields,rendered):
        audit_rows.append(dict(table='S13',source_file=str((local/name).relative_to(root)),
            source_sha256=sha(local/name),selector=json.dumps(selector),source_fields=json.dumps(fields),
            exact_source_values=json.dumps([r[f] for f in fields]),rendered_row=rendered,status='pending'))
    primary=[r for r in local_read('whatif_primary.csv') if r['scope']=='pooled']
    paired=[r for r in local_read('whatif_paired_feature.csv') if r['scope']=='pooled' and r['feature_contrast']=='LKS_minus_ACC']
    dose=[r for r in local_read('whatif_dose.csv') if r['scope']=='pooled']
    joint=[r for r in local_read('whatif_joint.csv') if r['scope']=='pooled']
    assert (len(primary),len(paired),len(dose),len(joint))==(12,2,10,4)
    assert all(r['status']=='estimated' and int(float(r['simultaneous_family_estimable']))==12 for r in primary)
    assert all(int(r['n_eligible'])==571 and r['analysis']=='post_primary_exploratory' for r in paired)
    assert all(int(r['n_eligible'])==0 and r['status']=='insufficient_support' and not r['estimate'] for r in joint)
    labels={'trust_pre_overall':'Overall trust','trust_pre_acc':'ACC trust','trust_pre_lks':'LKS trust',
            'accept_pre_delegate':'Delegation willingness','accept_pre_monitor_raw':'Supervision need',
            'accept_pre_distract':'Non-driving willingness'}
    def section(title):return r'\multicolumn{6}{@{}l}{\textbf{'+title+r'}} \\'
    body=[section('A. Primary one-point perturbations')]
    for r in primary:
        rendered=row(labels[r['context']],f"${int(r['contrast']):+d}$",r['n_eligible'],num(r['estimate'],4),
                     ci(r,digits=4),ci(r,'simultaneous_ci_low','simultaneous_ci_high',4))
        body.append(rendered)
        keep_local('whatif_primary.csv',r,{'context':r['context'],'contrast':r['contrast'],'scope':'pooled'},
                   ['n_eligible','estimate','ci_low','ci_high','simultaneous_ci_low','simultaneous_ci_high'],rendered)
    body += [r'\addlinespace[5pt]',section('B. Paired LKS-minus-ACC response difference (exploratory)')]
    for r in paired:
        rendered=row('LKS $-$ ACC',f"${int(r['step']):+d}$",r['n_eligible'],num(r['estimate'],4),ci(r,digits=4),r'\textemdash')
        body.append(rendered)
        keep_local('whatif_paired_feature.csv',r,{'feature_contrast':r['feature_contrast'],'step':r['step'],'scope':'pooled'},
                   ['n_eligible','estimate','ci_low','ci_high'],rendered)
    body += [r'\addlinespace[5pt]',section('C. Five-point dose curves on common supported sets')]
    for r in dose:
        rendered=row(labels[r['context']],f"${int(r['contrast']):+d}$",r['n_eligible'],num(r['estimate'],4),ci(r,digits=4),r'\textemdash')
        body.append(rendered)
        keep_local('whatif_dose.csv',r,{'context':r['context'],'contrast':r['contrast'],'scope':'pooled'},
                   ['n_eligible','estimate','ci_low','ci_high'],rendered)
    body += [r'\addlinespace[5pt]',section('D. Joint ACC +1 and LKS +1')]
    rendered=r'Joint four-corner support & $+1,+1$ & 0 & \multicolumn{3}{l}{Not estimated: no eligible participants} \\'
    body.append(rendered)
    for r in joint:
        keep_local('whatif_joint.csv',r,{'contrast':r['contrast'],'scope':'pooled'},
                   ['n_eligible','estimate','ci_low','ci_high','status'],rendered)
    emit(13,'whatif_summary',
        'Support-restricted held-out model responses to changes in initial attitude inputs. '
        r'$\Delta$ is changed-input minus original-input predicted event-mean risk, first averaged '
        'across observed events within each participant and then equally across eligible participants.',
        r'@{}lrrrrr@{}',['Input / comparison','Step','$N$',r'Mean $\Delta$',r'Pointwise 95\% CI',r'Simultaneous 95\% CI'],body,
        'Part A uses the same supported participants for the two signs of each item; the six item-specific '
        'sets differ. Support requires at least ten of 100 unique training neighbours at the original '
        'and each changed integer value, together with the frozen distance-radius rule. All intervals use '
        '2,000 shared participant-bootstrap draws with the five held-out models fixed. The simultaneous '
        'band applies only to the 12 pooled primary contrasts and uses the fixed-SE maximum absolute '
        'bootstrap deviation. Part B is a separately labelled post-primary comparison on 571 common '
        'participants. Part C requires support at all five values within each item; step zero is the '
        'unchanged-input reference. Part D has no supported four-corner observations: effects and intervals '
        'are not estimated. A dash denotes that a simultaneous interval is not assigned to that secondary '
        'analysis. Predictions are model sensitivities, not intervention effects. Complete block, threshold '
        'and baseline-stratified results remain in Supplementary Data.',
        [local/name for name in ['whatif_primary.csv','whatif_paired_feature.csv','whatif_dose.csv','whatif_joint.csv']],
        {'n_display_rows':25,'display_parts':{'A':12,'B':2,'C':10,'D':1},
         'joint_source_rows_consolidated':4,'joint_status':'insufficient_support; no invented zero effect',
         'ci_scope':'fixed-model shared participant bootstrap; simultaneous band only A'})

    # Every new body row must contain exactly the values selected from its named
    # source row. The source values are preserved as strings for lossless audit.
    for r in audit_rows:
        path=out/produced[r['table']]
        normalized = re.sub(r'\bB[1-4]\b', lambda m: {'B1':'LC','B2':'SVM','B3':'HB','B4':'MB'}[m.group()], r['rendered_row'])
        assert normalized in path.read_text(), (r['table'],r['selector'])
        r['status']='source_row_display_match'
        r['output_file']=str(path.relative_to(root))
        r['output_sha256']=sha(path)
    with (reportdir/'supplement_table_source_value_audit.csv').open('w',newline='') as f:
        writer=csv.DictWriter(f,fieldnames=list(audit_rows[0]));writer.writeheader();writer.writerows(audit_rows)
    inherited=[]
    for i, before in inherited_before.items():
        entries=[t for t in metadata['tables'] if Path(t['file']).name.startswith(f'table_s{i}_')]
        assert len(entries)==1
        target=root/entries[0]['file']; after=target.read_text()
        normalize=lambda s:'\n'.join(line for line in s.splitlines() if not line.startswith('%'))
        assert normalize(before)==normalize(after),f'S{i} changed beyond generator comments'
        inherited.append(dict(table=f'S{i}',status='identical_body_caption_notes_layout_to_frozen_v3',
                              output_file=str(target.relative_to(root)),sha256=sha(target),
                              sources=entries[0]['sources']))
    audit=dict(status='pass',scope='S7--S13 every displayed result row cross-referenced to exact saved CSV values; S1--S6 regenerated from saved CSV sources',
               new_result_rows=179,new_source_row_records=len(audit_rows),inherited_tables=inherited,
               table_row_counts={'S7':29,'S8':24,'S9':26,'S10':9,'S11':36,'S12':30,'S13':25},
               new_table_files={k:{'path':str((out/v).relative_to(root)),'sha256':sha(out/v)} for k,v in produced.items()},
               new_analysis=False,script_sha256=sha(Path(__file__)),
               row_audit_sha256=sha(reportdir/'supplement_table_source_value_audit.csv'))
    (reportdir/'supplement_table_source_value_audit.json').write_text(json.dumps(audit,indent=2,ensure_ascii=False)+'\n')
