#!/usr/bin/env python3
"""Format saved round-2 CSV results as LaTeX supplemental tables; no estimation.

Requires only the Python standard library. Run from any directory:
    python presentation/tables_core.py [--project-root ROOT]
LaTeX dependencies: the manuscript class, booktabs and longtable. S1--S6 format saved values; S7--S13 use longtables with repeated headers.
Source values remain unchanged; only labels, ordering and formatting are applied.
"""
from __future__ import annotations
import re
import argparse
import csv
import hashlib
import json
from pathlib import Path

PROTOCOLS = [
    ('participant_5fold', 'New participants'),
    ('leave_country_out', 'Held-out country'),
    ('event_group_5fold', 'New events'),
    ('crossed_participant_event_5x5', r'New participants + events'),
]
ITEMS = [('overall', 'Overall trust'), ('acc', 'ACC trust'), ('lks', 'LKS trust'),
         ('delegate', 'Delegate driving'), ('monitor_raw', 'Need for supervision'),
         ('distract', 'Non-driving activities')]
SHORT_COUNTRIES = {
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'United States of America': 'United States',
}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tex(s):
    return str(s).replace('&', r'\&').replace('%', r'\%').replace('_', r'\_')


def num(value, digits=3):
    out = f'{float(value):.{digits}f}'
    # Do not display a signed zero after rounding.
    if out.startswith('-') and float(out) == 0:
        out = out[1:]
    return out


def ci(row, low='ci_low', high='ci_high', digits=3):
    return rf'$[{num(row[low], digits)},\ {num(row[high], digits)}]$'


def qvalue(value):
    x = float(value)
    if x < .001:
        return r'$<0.001$'
    return num(x, 3)


def row(*cells):
    return ' & '.join(map(str, cells)) + r' \\'


def table(number, label, caption, body, footnote='', tabcolsep='4pt', placement='htbp'):
    return '\n'.join([
        '% Generated by presentation/tables_core.py.',
        '% Saved-result conversion only; edit the generator rather than this file.',
        rf'\begin{{table}}[{placement}]', r'\centering', r'\small',
        rf'\setlength{{\tabcolsep}}{{{tabcolsep}}}', r'\renewcommand{\arraystretch}{1.04}',
        rf'\caption{{{caption}}}', rf'\label{{tab:{label}}}',
        *body,
        *([r'\par\smallskip', r'\begin{minipage}{\linewidth}\small\raggedright', footnote,
           r'\end{minipage}'] if footnote else []),
        r'\end{table}', '',
    ])


def main(root):
    source = root / 'outputs/core/tables'
    out = root / 'outputs/presentation/tables'
    reports = root / 'outputs/presentation/reports'
    out.mkdir(parents=True, exist_ok=True); reports.mkdir(parents=True, exist_ok=True)
    metadata = {'operation': 'saved CSV to LaTeX formatting only; no estimation or resampling',
                'script_sha256': digest(Path(__file__)), 'tables': [],
                'display_rounding': {'effect_and_means': 3, 'prediction_r2_and_increment': 4,
                                     'q_below_0.001': '<0.001 (display only; exact source values retained)',
                                     'q_other': '3 decimal places'},
                'protocol_labels': dict(PROTOCOLS), 'country_label_aliases': SHORT_COUNTRIES}

    def read(name):
        with (source / name).open(newline='', encoding='utf-8') as f:
            return list(csv.DictReader(f))

    def write(name, content, filenames, conversion):
        path = out / name
        if name.startswith(('table_s2_', 'table_s3_', 'table_s4_', 'table_s5_')):
            # Preserve all cells, font sizes and numeric formatting; distribute
            # the remaining line width among column gaps, without graphic scaling.
            content = content.replace(r'\begin{tabular}{@{}',
                r'\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}')
            content = content.replace(r'\end{tabular}', r'\end{tabular*}')
            conversion['layout'] = 'tabular* at linewidth; stretch column gaps only; unchanged small font'
        else:
            conversion['layout'] = 'original natural-width tabular; unchanged font and cells'
        content = re.sub(r'\bB[1-4]\b', lambda m: {'B1':'LC','B2':'SVM','B3':'HB','B4':'MB'}[m.group()], content)
        path.write_text(content, encoding='utf-8')
        metadata['tables'].append({'file': str(path.relative_to(root)),
            'sha256': digest(path), 'sources': [{
                'path': str((Path(f) if isinstance(f,Path) else source / f).relative_to(root)), 'sha256': digest(Path(f) if isinstance(f,Path) else source / f)
            } for f in filenames], **conversion})

    inherited_before = {}  # Regenerate from numeric sources, without historical TeX inputs.

    # S1: all country rows, retained source ordering (descending N).
    countries = read('d2_country_coverage.csv')
    assert len(countries) == 29 and len({r['country'] for r in countries}) == 29
    assert sum(int(r['n_completed_licensed']) for r in countries) == 2164
    assert sum(int(r['n_valid_risk_ratings']) for r in countries) == 179966
    assert sum(int(r['n_zero_no_operation']) for r in countries) == 1810
    body = [r'\begin{tabular}{@{}lrrr@{}}', r'\toprule',
            row('Country', 'Participants', 'Valid ratings', 'No operation'), r'\midrule']
    for r in countries:
        body.append(row(tex(SHORT_COUNTRIES.get(r['country'], r['country'])),
                        f"{int(r['n_completed_licensed']):,}", f"{int(r['n_valid_risk_ratings']):,}",
                        f"{int(r['n_zero_no_operation']):,}"))
    body += [r'\midrule', row('Total', '2,164', '179,966', '1,810'), r'\bottomrule', r'\end{tabular}']
    write('table_s1_country.tex', table(1, 's1_country',
        'Country coverage in the completed, licensed sample. Participant counts are persons; '
        'valid-rating and no-operation counts are repeated clip-level responses. Valid risk ratings '
        'are 1--10; a recorded zero indicates no operation and is excluded from valid ratings. '
        'All 29 countries are retained.', body,
        'United Kingdom abbreviates United Kingdom of Great Britain and Northern Ireland; '
        'United States abbreviates United States of America. No uncertainty intervals are reported for these counts.'),
        ['d2_country_coverage.csv'], {'n_source_rows': 29, 'n_display_rows_excluding_total': 29,
        'fields': {'Country':'country', 'Participants':'n_completed_licensed',
                   'Valid ratings':'n_valid_risk_ratings', 'No operation':'n_zero_no_operation'},
        'total_row': 'column sums, checked against 2164 / 179966 / 1810'})

    # S2: saved paired contrasts, no recomputation of test statistics or intervals.
    contrasts = read('a2_position_contrasts.csv')
    assert len(contrasts) == 21
    body = [r'\begin{tabular}{@{}lcrrrr@{}}', r'\toprule',
            row('Block', 'Clips', '$N$', r'$\Delta$', r'95\% CI', '$q$'), r'\midrule']
    previous = None
    for r in contrasts:
        if previous is not None and previous != r['scenario']: body.append(r'\addlinespace[2pt]')
        body.append(row(r['scenario'], rf"${r['first']}\rightarrow {r['last']}$", f"{int(r['n']):,}",
                        num(r['delta']), ci(r), qvalue(r['q'])))
        previous = r['scenario']
    body += [r'\bottomrule', r'\end{tabular}']
    write('table_s2_contrasts.tex', table(2, 's2_contrasts',
        'Paired clip-position contrasts within questionnaire blocks. '
        r'$\Delta$ is the later-minus-earlier participant mean risk difference, in rating points '
        '(valid scores 1--10). $N$ counts participants with both clip-position means. '
        r'Pointwise 95\% percentile confidence intervals use 2,000 participant bootstrap draws. '
        '$q$ values are Benjamini--Hochberg adjustments of two-sided paired $t$ tests across all 21 contrasts.', body,
        'Within each participant, valid ratings are averaged across assigned events at each clip position. '
        'Intervals condition on the observed stimulus library; zeros denoting no operation are omitted.', tabcolsep='3.6pt'),
        ['a2_position_contrasts.csv'], {'n_source_rows':21,'n_display_rows':21,
        'fields':{'Block':'scenario','Clips':['first','last'],'N':'n','delta':'delta',
                  'CI':['ci_low','ci_high'],'q':'q'},
        'ci_scope':'2000 paired whole-participant bootstrap draws, pointwise 95%; fixed stimulus library',
        'q_scope':'BH across 21 saved two-sided paired t tests'})

    # S3: 12 full-model/baseline R2 cells and all 8 saved same-model increments.
    performance = read('m2_performance.csv'); increments = read('m2_person_increment.csv')
    weighted = read('m2_participant_weighted_metrics.csv')
    weighted_lookup = {(r['protocol'], r['model']):r for r in weighted}
    assert all(r['evaluation']=='equal_participant_weights_same_predictions' for r in weighted)
    models = ['Training event/block mean', 'Ridge', 'LightGBM']
    lookup = {(r['protocol'], r['model']):r for r in performance}
    assert len(increments) == 8
    body = [r'\begin{tabular}{@{}lrrr@{}}', r'\toprule',
            r'\multicolumn{4}{@{}l}{\textbf{A. Out-of-fold prediction $R^2$}} \\',
            row('Test target', 'Event/block mean', 'Ridge', 'LightGBM'), r'\midrule']
    for key, label in PROTOCOLS:
        body.append(row(label, *[num(lookup[(key, m)]['r2'],4) for m in models]))
    body += [r'\bottomrule',r'\end{tabular}',r'\par\medskip',
             r'\begin{tabular}{@{}llrr@{}}',r'\toprule',
             r'\multicolumn{4}{@{}l}{\textbf{B. Added participant attributes: same-model comparison}} \\',
             row('Test target','Model',r'$\Delta R^2$',r'95\% CI'),r'\midrule']
    increments_map = {(r['protocol'],r['model']):r for r in increments}
    for index,(key,label) in enumerate(PROTOCOLS):
        if index: body.append(r'\addlinespace[2pt]')
        for j,model in enumerate(['Ridge','LightGBM']):
            r = increments_map[(key,model)]
            body.append(row(label if j==0 else '', model, num(r['increment_r2'],4),
                ci(r,'person_increment_r2_ci_low','person_increment_r2_ci_high',4)))
    body += [r'\bottomrule',r'\end{tabular}',r'\par\medskip',
             r'\begin{tabular}{@{}lrrr@{}}',r'\toprule',
             r'\multicolumn{4}{@{}l}{\textbf{C. Participant-weighted $R^2$: same predictions}} \\',
             row('Test target','Event/block mean','Ridge','LightGBM'),r'\midrule']
    for key, label in PROTOCOLS:
        body.append(row(label,*[num(weighted_lookup[(key,m)]['r2'],4) for m in models]))
    body += [r'\bottomrule',r'\end{tabular}']
    write('table_s3_prediction.tex', table(3,'s3_prediction',
        r'Event-mean risk prediction under four held-out protocols. $R^2$ and $\Delta R^2$ are unitless. '
        'Part A uses the saved training event/block-mean baseline and full-attribute Ridge and LightGBM models. '
        'Part B compares each full-attribute model with the same algorithm using event/block identity alone. '
        'Part C assigns equal total weight to each participant, using the same saved predictions without refitting. '
        r'Pointwise 95\% percentile intervals use 1,000 paired participant-cluster bootstrap draws of fixed out-of-fold predictions.',body,
        'Each row uses 34,566 valid event means from 2,164 participants. '
        'New-participant and new-event protocols use five folds; the joint protocol crosses five participant and five event folds. '
        'Held-out country uses leave-one-country-out evaluation. New-event evaluation may include participants seen in training. '
        'The event/block-mean baseline falls back to the training block mean for unseen events. '
        'Bootstrap intervals do not refit models or resample stimuli.', tabcolsep='3pt'),
        ['m2_performance.csv','m2_person_increment.csv','m2_participant_weighted_metrics.csv'], {
        'n_source_performance_rows':len(performance),'n_selected_performance_rows':12,
        'n_source_participant_weighted_rows':len(weighted),'n_selected_participant_weighted_rows':12,
        'participant_weighted_evaluation':'equal_participant_weights_same_predictions',
        'performance_filter':{'model':models},'performance_field':'r2',
        'n_increment_rows':8,'increment_fields':['increment_r2','person_increment_r2_ci_low','person_increment_r2_ci_high'],
        'ci_scope':'1000 paired participant-cluster draws of fixed OOF predictions; pointwise 95%'})

    # S4: harmonized saved 2000-draw mean and paired-change intervals.
    harmonized = root / 'outputs/prepost/tables/prepost_harmonized.csv'
    with harmonized.open(newline='',encoding='utf-8') as f: prepost=list(csv.DictReader(f))
    pp={r['item']:r for r in prepost}
    assert len(prepost)==6 and all(int(r['n'])==2164 and int(r['bootstrap_draws'])==2000 for r in prepost)
    body=[r'\begin{tabular}{@{}lrrr@{}}',r'\toprule',
          row('Item',r'Pre mean [95\% CI]',r'Post mean [95\% CI]',r'$\Delta$ [95\% CI]'),r'\midrule']
    for item,label in ITEMS:
        r=pp[item]
        cells=[num(r[metric+'_mean'])+' '+ci(r,metric+'_ci_low',metric+'_ci_high') for metric in ['pre','post','delta']]
        body.append(row(label,*cells))
    body += [r'\bottomrule',r'\end{tabular}']
    write('table_s4_prepost.tex',table(4,'s4_prepost',
        'Six original pre/post items in 2,164 paired participants. Scores are 0--10 and zero is valid. '
        r'Means and $\Delta$ (post minus pre) are in item-rating points. '
        r'Intervals are pointwise 95\% percentile intervals from 2,000 paired participant bootstrap draws.',body,
        'Need for supervision retains the original direction: higher values indicate greater supervision need. '
        'Items are reported separately. Mean and change intervals use the same harmonized bootstrap draw set. '
        'These intervals are not simultaneous.',tabcolsep='3pt'), [harmonized],{
        'n_source_rows':6,'n_display_rows':6,'item_order':[x[0] for x in ITEMS],
        'fields':{metric:[metric+'_mean',metric+'_ci_low',metric+'_ci_high'] for metric in ['pre','post','delta']},
        'ci_scope':'2000 paired participant bootstrap draws from prepost_harmonized.csv; pointwise 95%'})

    # S5: two requested comparisons only; participant intervals, not country intervals.
    trust=read('a2_trust_cv_increment.csv')
    refs=[('pre_task_plus_response','A. Added mean risk, excursion and late change'),
          ('pre_task_plus_mean_risk_response','B. Added excursion and late change above mean risk')]
    selection=[r for r in trust if r['feature_set']=='pre_task_plus_both' and r['reference_feature_set'] in {x[0] for x in refs}]
    assert len(selection)==12 and all(int(r['n'])==2164 for r in selection)
    smap={(r['reference_feature_set'],r['protocol'],r['item']):r for r in selection}
    body=[]
    for group_index,(ref,title) in enumerate(refs):
        if group_index:body.append(r'\par\medskip')
        body += [r'\begin{tabular}{@{}llrr@{}}',r'\toprule',
                 r'\multicolumn{4}{@{}l}{\textbf{' + title + r'}} \\',
                 row('Test target','Trust outcome',r'$\Delta R^2$',r'95\% CI'),r'\midrule']
        for index,(key,label) in enumerate(PROTOCOLS[:2]):
            if index:body.append(r'\addlinespace[2pt]')
            for j,(item,item_label) in enumerate(ITEMS[:3]):
                r=smap[(ref,key,item)]
                body.append(row(label if j==0 else '',item_label,num(r['delta_r2'],4),
                                ci(r,'delta_ci_low','delta_ci_high',4)))
        body += [r'\bottomrule',r'\end{tabular}']
    write('table_s5_trust_prediction.tex',table(5,'s5_trust_prediction',
        'Incremental prediction of post-task trust ($N=2{,}164$ per outcome and protocol). '
        r'$\Delta R^2$ is unitless, expanded minus reference-model out-of-fold $R^2$. '
        'All models include pre-task attributes and operated-response fraction; part B also includes mean risk in its reference model. '
        r'Pointwise 95\% percentile confidence intervals use 2,000 paired participant bootstrap draws of fixed out-of-fold predictions.',body,
        'The expanded feature set is identical in parts A and B. Excursion and late change use peak positions selected only in training data. '
        'Intervals condition on observed countries and stimuli and do not include model-refitting uncertainty. '
        'These are unadjusted pointwise participant intervals, not country-cluster or simultaneous six-comparison intervals.',tabcolsep='3pt'),
        ['a2_trust_cv_increment.csv'],{'n_source_rows':len(trust),'n_selected_rows':12,
        'filter':{'feature_set':'pre_task_plus_both','reference_feature_set':[x[0] for x in refs]},
        'fields':{'delta_R2':'delta_r2','CI':['delta_ci_low','delta_ci_high']},
        'not_used':['delta_ci_low_country_cluster','delta_ci_high_country_cluster'],
        'ci_scope':'2000 paired participant bootstrap draws of fixed OOF predictions; pointwise 95%; no multiplicity adjustment'})

    # S6: saved HC1 coefficients and confidence intervals; no refitting.
    associations=read('a2_trust_risk_associations.csv')
    expected_features=[('mean_risk','Mean risk'),('excursion','Excursion'),
                       ('late_change','Late change'),('positive_fraction','Response fraction')]
    assert len(associations)==12 and all(int(r['n'])==2158 for r in associations)
    amap={(r['item'],r['feature']):r for r in associations}
    assert set(amap)=={(item,feature) for item,_ in ITEMS[:3] for feature,_ in expected_features}
    assert all(r['family']=='12_risk_trust_associations' for r in associations)
    body=[r'\begin{tabular}{@{}llrrrr@{}}',r'\toprule',
          row('Trust outcome','Predictor','Estimate',r'HC1 95\% CI','$q$','$N$'),r'\midrule']
    for i,(item,label) in enumerate(ITEMS[:3]):
        if i:body.append(r'\addlinespace[3pt]')
        for j,(feature,feature_label) in enumerate(expected_features):
            r=amap[(item,feature)]
            body.append(row(label if j==0 else '',feature_label,num(r['estimate']),ci(r),qvalue(r['q']),f"{int(r['n']):,}"))
    body += [r'\bottomrule',r'\end{tabular}']
    write('table_s6_risk_trust_associations.tex',table(6,'s6_risk_trust_associations',
        'Adjusted associations of risk-derived predictors with post-task trust, corresponding to main Fig. 5b. '
        'Coefficients are in trust-rating points per standard deviation of the displayed predictor. '
        r'Intervals are pointwise 95\% confidence intervals from heteroskedasticity-robust HC1 covariance; '
        '$q$ values are Benjamini--Hochberg adjustments across the 12 displayed associations.',body,
        'All models use 2,158 complete participants and adjust for the corresponding initial trust item, '
        'the four displayed predictors, age, driving experience, gender and country. '
        'Response fraction is the proportion of assigned video-risk ratings that were operated. '
        'Coefficients, intervals and adjusted test results are copied from the saved association table.',tabcolsep='4pt',placement='!htbp'),
        ['a2_trust_risk_associations.csv'],{'n_source_rows':12,'n_display_rows':12,
        'fields':{'outcome':'item','predictor':'feature','estimate':'estimate','CI':['ci_low','ci_high'],'q':'q','N':'n'},
        'ci_scope':'saved pointwise HC1 95% intervals; no bootstrap or model refit',
        'q_scope':'BH across 12 risk-derived-predictor by trust-outcome associations'})

    append_full_saved_tables(root, read, write, table, row, num, ci, qvalue, tex, metadata, inherited_before)
    metadata['output_count']=len(metadata['tables'])
    (reports/'supplement_table_manifest.json').write_text(json.dumps(metadata,indent=2,ensure_ascii=False)+'\n')
    print(json.dumps({'output_count':len(metadata['tables']), 'output_directory':str(out),
                      'source_rows_displayed':[29,21,'12 pooled R2 cells + 8 increments + 12 participant-weighted R2 cells',6,12,12,29,24,26,9,36,30,25]},indent=2))


from .full_tables import append_full_saved_tables

